#ifndef ALPHA_RECEIVER_HPP
#define ALPHA_RECEIVER_HPP

#include "spsc_ring_buffer.hpp"
#include <cstdint>
#include <cstring>

/**
 * AlphaSignal: A trading signal consumed by the hot path.
 *
 * P0 fixes updated (from DEEP_AUDIT_2026-09-26.es.md):
 *   - Added Type enum (WHALE_TRADE, HUMAN_SIGNAL, ML_MODEL, UNKNOWN)
 *   - Added confidence, q_value, timestamp_ns, token_fingerprint, direction_hint
 *
 * This struct is designed for zero-copy SPSC ring buffer transfer:
 * - All fields are POD (trivially copyable)
 * - No std::string or heap allocation
 * - market_slug is a fixed char[32] buffer
 *
 * In production, AlphaSignal is populated by:
 *   - ML model inference pipeline (via shared memory)
 *   - External alpha service (via network or shared memory)
 *   - Backtesting replay (from file)
 *
 * In simulation/paper-trading mode, it's generated by a deterministic
 * PRNG-based signal generator.
 *
 * CRITICAL: Must remain trivially copyable for SPSC_RingBuffer memcpy.
 */
struct AlphaSignal {
    // Signal source / type classification
    enum class Type : uint8_t {
        WHALE_TRADE   = 0,  // Large on-chain trade detected
        HUMAN_SIGNAL  = 1,  // Manual trader signal
        ML_MODEL      = 2,  // ML model prediction
        UNKNOWN       = 3   // Unclassified / fallback
    };

    char market_slug[32];           // Fixed-size — no heap allocation
    uint64_t price;                 // Expected price (* 1e6)
    uint64_t size;                  // Size in units (* 1e6)
    uint64_t nonce;                 // Unique nonce for this signal
    uint64_t salt;                  // Salt for order ID generation
    int64_t  ev_per_dollar;         // Expected value per dollar (scaled * 1e6)
    uint8_t  side;                  // 0 = BUY, 1 = SELL
    bool     valid;                 // Signal validity flag

    // ─── P0.1: New fields for signal metadata ─────────────────────
    uint8_t  type;                  // AlphaSignal::Type enum value (uint8_t for trivial copy)
    double   confidence;            // Signal confidence (0.0 - 1.0)
    double   q_value;               // Q-value from RL model (action-value estimate)
    uint64_t timestamp_ns;          // Signal generation timestamp (nanoseconds since epoch)
    uint64_t token_fingerprint;     // Hash of market_slug for fast dedup/compare
    uint8_t  direction_hint;        // 0=buy forced, 1=sell forced, 2=engine decides

    AlphaSignal()
        : price(0), size(0), nonce(0), salt(0), ev_per_dollar(0), side(0), valid(false),
          type(static_cast<uint8_t>(Type::UNKNOWN)),
          confidence(0.0), q_value(0.0), timestamp_ns(0), token_fingerprint(0),
          direction_hint(2) {
        memset(market_slug, 0, sizeof(market_slug));
    }
};

/**
 * AlphaReceiver: Polls an SPSC ring buffer for incoming signals.
 * In simulation mode, provides a push() method to inject signals.
 */
class AlphaReceiver {
public:
    explicit AlphaReceiver(SPSC_RingBuffer<AlphaSignal>& queue)
        : queue_(queue) {}

    /**
     * Try to receive a signal. Returns nullptr if queue is empty.
     * Hot path — O(1), lock-free.
     *
     * P0 fix: SPSC_RingBuffer::try_pop() returns std::optional<AlphaSignal>,
     * not a raw pointer. We store the result in a thread-local buffer.
     */
    AlphaSignal* try_receive() {
        auto result = queue_.try_pop();
        if (result) {
            last_signal_ = std::move(*result);
            return &last_signal_;
        }
        return nullptr;
    }

    /**
     * Inject a signal (simulation/paper-trading mode only).
     */
    bool inject(const AlphaSignal& signal) {
        return queue_.try_push(signal);
    }

private:
    SPSC_RingBuffer<AlphaSignal>& queue_;
    AlphaSignal last_signal_;
};

#endif // ALPHA_RECEIVER_HPP
