#ifndef ALPHA_RECEIVER_HPP
#define ALPHA_RECEIVER_HPP

#include "spsc_ring_buffer.hpp"
#include <cstdint>

/**
 * AlphaSignal: A trading signal consumed by the hot path.
 *
 * This struct is designed for zero-copy SPSC ring buffer transfer:
 * - All fields are POD (trivially copyable)
 * - No std::string or heap allocation
 * - market_slug is a fixed char[32] buffer
 *
 * In production, AlphaSignal is populated by:
 *   - ML model inference pipeline (via shared memory)
 *   - External alpha service (via network or shared memory)
 *   - Backtesting replay (from file)
 *
 * In simulation/paper-trading mode, it's generated by a deterministic
 * PRNG-based signal generator.
 */
struct AlphaSignal {
    char market_slug[32];           // Fixed-size — no heap allocation
    uint64_t price;                 // Expected price (* 1e6)
    uint64_t size;                  // Size in units (* 1e6)
    uint64_t nonce;                 // Unique nonce for this signal
    uint64_t salt;                  // Salt for order ID generation
    int64_t  ev_per_dollar;         // Expected value per dollar (scaled * 1e6)
    uint8_t  side;                  // 0 = BUY, 1 = SELL
    bool     valid;                 // Signal validity flag

    AlphaSignal() : price(0), size(0), nonce(0), salt(0), ev_per_dollar(0), side(0), valid(false) {
        memset(market_slug, 0, sizeof(market_slug));
    }
};

/**
 * AlphaReceiver: Polls an SPSC ring buffer for incoming signals.
 * In simulation mode, provides a push() method to inject signals.
 */
class AlphaReceiver {
public:
    explicit AlphaReceiver(SPSC_RingBuffer<AlphaSignal>& queue)
        : queue_(queue) {}

    /**
     * Try to receive a signal. Returns nullptr if queue is empty.
     * Hot path — O(1), lock-free.
     */
    AlphaSignal* try_receive() {
        return queue_.try_pop();
    }

    /**
     * Inject a signal (simulation/paper-trading mode only).
     */
    bool inject(const AlphaSignal& signal) {
        return queue_.try_push(signal);
    }

private:
    SPSC_RingBuffer<AlphaSignal>& queue_;
};

#endif // ALPHA_RECEIVER_HPP
