#ifndef EIP712_SIGNER_HPP
#define EIP712_SIGNER_HPP

#include <array>
#include <cstdint>
#include <cstring>
#include <vector>
#include <stdexcept>
#include <string>
#include <openssl/evp.h>
#include <openssl/ec.h>
#include <openssl/bn.h>
#include <openssl/err.h>
#include <openssl/sha.h>

/**
 * EIP712Signer: Production-ready cryptographic signer for Polygon/EIP-712 (Polymarket CLOB V2).
 *
 * Uses OpenSSL 3.x (EVP API / ECDSA legacy API) for ECDSA over secp256k1.
 * Includes full Keccak-256 (Keccak-f[1600]) implementation with chain-based
 * ρ+π per the XKCP reference — NOT SHA3-256 (which uses suffix 0x06; Keccak-256
 * uses suffix 0x01).
 */
struct OrderParams {
    uint64_t salt;
    uint8_t maker[20];
    uint8_t taker[20];
    uint64_t price;
    uint64_t size;
    uint64_t nonce;
    uint8_t side;
} __attribute__((packed));

#pragma GCC push_options
#pragma GCC optimize ("-O3")

// --- Keccak-256 (FIPS 202 compliant, self-contained, zero-alloc hot path) ---
// Implements Keccak-f[1600] permutation with rate 1088 bits, capacity 512 bits.
// Padding: pad10*1 with domain suffix 0x01 (Keccak-256, NOT SHA3-256's 0x06).
// Multi-block absorption supported for messages longer than 136 bytes.
// Reference: https://github.com/XKCP/XKCP (CompactFIPS202.py)

inline void keccak_f1600(uint64_t A[25]) {
    // Keccak-f[1600] round constants, generated by the standard LFSR
    // (poly 0x71). These are the VERIFIED values — see XKCP CompactFIPS202
    // and match OpenSSL / pycryptodome. (Earlier versions of this file used
    // a corrupted "standard table" that was wrong for rounds 13–23.)
    static const uint64_t RC[24] = {
        0x0000000000000001ULL, 0x0000000000008082ULL, 0x800000000000808AULL,
        0x8000000080008000ULL, 0x000000000000808BULL, 0x0000000080000001ULL,
        0x8000000080008081ULL, 0x8000000000008009ULL, 0x000000000000008AULL,
        0x0000000000000088ULL, 0x0000000080008009ULL, 0x000000008000000AULL,
        0x000000008000808BULL, 0x800000000000008BULL, 0x8000000000008089ULL,
        0x8000000000008003ULL, 0x8000000000008002ULL, 0x8000000000000080ULL,
        0x000000000000800AULL, 0x800000008000000AULL, 0x8000000080008081ULL,
        0x8000000000008080ULL, 0x0000000080000001ULL, 0x8000000080008008ULL
    };

    for (int round = 0; round < 24; round++) {
        // --- θ (Theta) ---
        uint64_t C[5], D[5];
        for (int x = 0; x < 5; x++)
            C[x] = A[x] ^ A[x + 5] ^ A[x + 10] ^ A[x + 15] ^ A[x + 20];
        for (int x = 0; x < 5; x++)
            D[x] = C[(x + 4) % 5] ^ ((C[(x + 1) % 5] << 1) | (C[(x + 1) % 5] >> 63));
        for (int x = 0; x < 5; x++)
            for (int y = 0; y < 5; y++)
                A[x + y * 5] ^= D[x];

        // --- ρ (Rho) + π (Pi) — chain-based per XKCP reference ---
        // Chain starts at (1,0). Each step moves to (y, (2x+3y)%5) and applies
        // rotation (t+1)*(t+2)/2 mod 64. This visits all 24 non-(0,0) positions
        // exactly once — equivalent to a static rotation table, but eliminates
        // any possibility of table-entry transcription errors.
        {
            int x = 1, y = 0;
            uint64_t current = A[x + y * 5];
            for (int t = 0; t < 24; t++) {
                int nx = y;
                int ny = (2 * x + 3 * y) % 5;
                uint64_t temp = A[nx + ny * 5];
                int shift = (int)(((t + 1) * (t + 2)) / 2) % 64;
                if (shift == 0)
                    A[nx + ny * 5] = current;
                else
                    A[nx + ny * 5] = (current << shift) | (current >> (64 - shift));
                current = temp;
                x = nx;
                y = ny;
            }
        }

        // --- χ (Chi) ---
        for (int y = 0; y < 5; y++) {
            uint64_t tmp[5];
            for (int x = 0; x < 5; x++)
                tmp[x] = A[x + y * 5];
            for (int x = 0; x < 5; x++)
                A[x + y * 5] = tmp[x] ^ ((~tmp[(x + 1) % 5]) & tmp[(x + 2) % 5]);
        }

        // --- ι (Iota) ---
        A[0] ^= RC[round];
    }
}

inline void keccak256_hash(const uint8_t* data, size_t len, uint8_t out[32]) {
    constexpr size_t RATE = 136;  // Keccak-256: rate = 1088 bits = 136 bytes
    uint64_t A[25] = {0};

    // --- Absorbing phase (multi-block support) ---
    size_t offset = 0;
    while (offset + RATE <= len) {
        for (size_t i = 0; i < RATE / 8; i++) {
            uint64_t word = 0;
            for (size_t k = 0; k < 8; k++)
                word |= (uint64_t)data[offset + i * 8 + k] << (8 * k);
            A[i] ^= word;
        }
        keccak_f1600(A);
        offset += RATE;
    }

    // Last block + padding (pad10*1 with suffix 0x01)
    uint8_t block[RATE] = {0};
    size_t remaining = len - offset;
    if (remaining > 0)
        memcpy(block, data + offset, remaining);
    block[remaining] ^= 0x01;       // domain suffix for Keccak-256
    block[RATE - 1] ^= 0x80;        // padding high bit
    for (size_t i = 0; i < RATE / 8; i++) {
        uint64_t word = 0;
        for (size_t k = 0; k < 8; k++)
            word |= (uint64_t)block[i * 8 + k] << (8 * k);
        A[i] ^= word;
    }
    keccak_f1600(A);

    // --- Squeeze phase (256 bits = 32 bytes) ---
    for (size_t i = 0; i < 32; i++)
        out[i] = (uint8_t)(A[i / 8] >> (8 * (i % 8)));
}

// --- EIP-712 Domain Separator ---
// Computes the EIP-712 domain separator hash from domain parameters.
// domainType is the EIP-712 type string, e.g.:
//   "EIP712Domain(string name,address verifyingContract)"
// domainData is the ABI-encoded domain data (name hash, version hash, chainId, verifyingContract).
//
// domainSeparator = keccak256(keccak256(domainType) ^^^ domainData)
inline void eip712_domain_separator(
    const std::string& domainType,
    const std::vector<uint8_t>& domainData,
    uint8_t out[32])
{
    uint8_t type_hash[32];
    keccak256_hash(reinterpret_cast<const uint8_t*>(domainType.data()),
                   domainType.size(), type_hash);

    std::vector<uint8_t> combined;
    combined.reserve(32 + domainData.size());
    combined.insert(combined.end(), type_hash, type_hash + 32);
    combined.insert(combined.end(), domainData.begin(), domainData.end());
    keccak256_hash(combined.data(), combined.size(), out);
}

// --- EIP-712 struct hash for OrderParams ---
// structHash = keccak256(typeHash ^^^ ABIEncode(params))
// ABI encoding: each field left-padded to 32 bytes (big-endian).
inline void eip712_order_struct_hash(
    const std::string& structType,
    const OrderParams& params,
    uint8_t out[32])
{
    uint8_t type_hash[32];
    keccak256_hash(reinterpret_cast<const uint8_t*>(structType.data()),
                   structType.size(), type_hash);

    constexpr size_t ENCODED_SIZE = 32 * 7;  // 7 fields, each 32 bytes
    uint8_t encoded[ENCODED_SIZE] = {0};     // MUST be zeroed — ABI pads to 32 bytes

    auto write_be64 = [](uint8_t* slot, uint64_t val) {
        // Zero the full 32-byte slot, then write value big-endian at the tail
        memset(slot, 0, 32);
        for (int i = 0; i < 8; i++)
            slot[31 - i] = (uint8_t)(val >> (8 * i));
    };
    auto write_addr = [](uint8_t* slot, const uint8_t addr[20]) {
        memset(slot, 0, 32);
        memcpy(slot + 12, addr, 20);
    };

    write_be64(encoded +   0, params.salt);
    write_addr(encoded +  32, params.maker);
    write_addr(encoded +  64, params.taker);
    write_be64(encoded +  96, params.price);
    write_be64(encoded + 128, params.size);
    write_be64(encoded + 160, params.nonce);
    write_be64(encoded + 192, params.side);

    std::vector<uint8_t> combined;
    combined.reserve(32 + ENCODED_SIZE);
    combined.insert(combined.end(), type_hash, type_hash + 32);
    combined.insert(combined.end(), encoded, encoded + ENCODED_SIZE);
    keccak256_hash(combined.data(), combined.size(), out);
}

// --- Recovery ID (v) computation ---
// Given (r, s, e) where e is the message hash as a big-endian integer,
// determines which recovery_id (0 or 1) corresponds to the signer's public key.
// EIP-155: s must be low (≤ n/2). If we flip s to low form, we must also flip parity.
// v = 27 + (recovered_parity XOR s_low_flip)
inline int compute_recovery_id(
    const EC_GROUP* group,
    const BIGNUM* r,
    const BIGNUM* s_low,
    const EC_POINT* Q,
    const unsigned char* msg_hash_32,
    BN_CTX* ctx)
{
    const BIGNUM* n = EC_GROUP_get0_order(group);
    BIGNUM* e = BN_bin2bn(msg_hash_32, 32, NULL);

    BIGNUM* r_inv = BN_mod_inverse(NULL, r, n, ctx);
    BIGNUM* s_new = BN_new();
    BIGNUM* e_new = BN_new();
    BN_mod_mul(s_new, r_inv, s_low, n, ctx);
    BN_mod_mul(e_new, r_inv, e, n, ctx);

    BIGNUM* neg_e_new = BN_new();
    BN_sub(neg_e_new, n, e_new);  // -e_new mod n

    int result = -1;
    for (int parity = 0; parity < 2; parity++) {
        EC_POINT* R = EC_POINT_new(group);
        if (!EC_POINT_set_compressed_coordinates(group, R, r, parity, ctx)) {
            EC_POINT_free(R);
            continue;
        }
        // Q_candidate = neg_e_new * G + s_new * R
        //            = r_inv * (s * R - e * G)  — the EIP-191 recovery formula
        EC_POINT* Q_cand = EC_POINT_new(group);
        EC_POINT_mul(group, Q_cand, neg_e_new, R, s_new, ctx);
        if (EC_POINT_cmp(group, Q_cand, Q, ctx) == 0)
            result = parity;
        EC_POINT_free(R);
        EC_POINT_free(Q_cand);
        if (result != -1) break;
    }

    BN_free(e);
    BN_free(r_inv);
    BN_free(s_new);
    BN_free(e_new);
    BN_free(neg_e_new);
    return result;
}

// --- EIP-712 Signer ---
class EIP712Signer {
public:
    explicit EIP712Signer(
        const std::vector<uint8_t>& private_key_bytes,
        const std::string& eip712_domain_type = "EIP712Domain(string name,address verifyingContract)",
        const std::vector<uint8_t>& domain_data = {})
        : pkey_(nullptr) {

        if (private_key_bytes.size() != 32)
            throw std::runtime_error("Private key must be 32 bytes.");

        // --- Load secp256k1 private key via OpenSSL 3.x EVP_PKEY ---
        EVP_PKEY_CTX* pctx = EVP_PKEY_CTX_new_id(EVP_PKEY_EC, nullptr);
        if (!pctx) handle_openssl_error("EVP_PKEY_CTX_new_id failed");

        if (EVP_PKEY_keygen_init(pctx) <= 0) handle_openssl_error("EVP_PKEY_keygen_init failed");
        if (EVP_PKEY_CTX_set_ec_paramgen_curve_nid(pctx, NID_secp256k1) <= 0)
            handle_openssl_error("Failed to set curve to secp256k1");

        if (EVP_PKEY_keygen(pctx, &pkey_) <= 0) handle_openssl_error("EVP_PKEY_keygen failed");

        const BIGNUM* priv_bn = BN_bin2bn(private_key_bytes.data(), 32, nullptr);
        EC_KEY* ec_key = EVP_PKEY_get1_EC_KEY(pkey_);
        if (!ec_key) handle_openssl_error("EVP_PKEY_get1_EC_KEY failed");
        if (EC_KEY_set_private_key(ec_key, priv_bn) != 1)
            handle_openssl_error("EC_KEY_set_private_key failed");

        const EC_GROUP* group = EC_KEY_get0_group(ec_key);
        EC_POINT* pub_key = EC_POINT_new(group);
        if (!EC_POINT_mul(group, pub_key, priv_bn, nullptr, nullptr, nullptr))
            handle_openssl_error("EC_POINT_mul failed");
        if (EC_KEY_set_public_key(ec_key, pub_key) != 1)
            handle_openssl_error("EC_KEY_set_public_key failed");

        if (EVP_PKEY_set1_EC_KEY(pkey_, ec_key) != 1)
            handle_openssl_error("EVP_PKEY_set1_EC_KEY failed");

        BN_free((BIGNUM*)priv_bn);
        EC_POINT_free(pub_key);
        EC_KEY_free(ec_key);
        EVP_PKEY_CTX_free(pctx);

        // --- Compute domain separator ---
        domain_type_ = eip712_domain_type;
        if (!domain_data.empty()) {
            eip712_domain_separator(eip712_domain_type, domain_data, domain_separator_);
        } else {
            memset(domain_separator_, 0, 32);
        }
    }

    ~EIP712Signer() {
        if (pkey_) EVP_PKEY_free(pkey_);
    }

    void set_domain(const std::string& domain_type,
                    const std::vector<uint8_t>& domain_data) {
        domain_type_ = domain_type;
        eip712_domain_separator(domain_type, domain_data, domain_separator_);
    }

    void sign_order(const OrderParams& params, std::array<uint8_t, 65>& out_signature) {
        // 1. Compute struct hash
        const std::string STRUCT_TYPE =
            "OrderParams(uint64 salt,address maker,address taker,uint64 price,uint64 size,uint64 nonce,uint8 side)";
        uint8_t struct_hash[32];
        eip712_order_struct_hash(STRUCT_TYPE, params, struct_hash);

        // 2. Build EIP-712 final hash: keccak256("\x19\x01" + domain + struct_hash)
        uint8_t final_payload[66];
        final_payload[0] = 0x19;
        final_payload[1] = 0x01;
        memcpy(final_payload + 2, domain_separator_, 32);
        memcpy(final_payload + 34, struct_hash, 32);

        uint8_t eip712_hash[32];
        keccak256_hash(final_payload, 66, eip712_hash);

        // 3. Sign the raw Keccak-256 hash with ECDSA — NO double-hashing.
        //    ECDSA_sign treats the 32-byte input as a pre-computed digest.
        EC_KEY* ec_key = EVP_PKEY_get1_EC_KEY(pkey_);
        if (!ec_key) handle_openssl_error("EVP_PKEY_get1_EC_KEY (sign) failed");

        const EC_GROUP* group = EC_KEY_get0_group(ec_key);
        const BIGNUM* n = EC_GROUP_get0_order(group);
        BN_CTX* ctx = BN_CTX_secure_new();

        unsigned int der_len = 0;
        alignas(8) unsigned char der_sig[72];
        if (ECDSA_sign(0, eip712_hash, 32, der_sig, &der_len, ec_key) != 1) {
            EC_KEY_free(ec_key);
            BN_CTX_free(ctx);
            handle_openssl_error("ECDSA_sign failed");
        }

        // 4. Parse DER to extract r and s
        const unsigned char* sig_ptr = der_sig;
        ECDSA_SIG* ec_sig = d2i_ECDSA_SIG(nullptr, &sig_ptr, der_len);
        if (!ec_sig) {
            EC_KEY_free(ec_key);
            BN_CTX_free(ctx);
            handle_openssl_error("d2i_ECDSA_SIG failed");
        }

        const BIGNUM* r_bn = ECDSA_SIG_get0_r(ec_sig);
        const BIGNUM* s_bn = ECDSA_SIG_get0_s(ec_sig);

        // 5. Normalize s to low form (EIP-2) and track parity flip
        BIGNUM* half_n = BN_new();
        BN_rshift(half_n, n, 1);
        BIGNUM* s_final = BN_new();
        int s_low_flip = 0;
        if (BN_cmp(s_bn, half_n) > 0) {
            BN_sub(s_final, n, s_bn);  // s' = n - s (low-s)
            s_low_flip = 1;
        } else {
            BN_copy(s_final, s_bn);
        }

        // 6. Recover public key to determine y-parity of R.
        // CRITICAL: pass the ORIGINAL s_bn (not s_final) to the recovery formula.
        // The formula Q = r_inv * (s * R - e * G) only holds for the original s.
        // When s is flipped to s' = n - s, the nonce point R' = -R has opposite
        // y-parity, which we correct by XORing recovered_parity with s_low_flip.
        const EC_POINT* Q = EC_KEY_get0_public_key(ec_key);
        int recovered_parity = compute_recovery_id(group, r_bn, s_bn, Q, eip712_hash, ctx);
        if (recovered_parity < 0) {
            EC_KEY_free(ec_key);
            BN_free(half_n); BN_free(s_final);
            BN_CTX_free(ctx);
            ECDSA_SIG_free(ec_sig);
            handle_openssl_error("Failed to compute recovery id (v value)");
        }

        int v = 27 + (recovered_parity ^ s_low_flip);

        // 7. Encode r || s || v
        BN_bn2binpad(r_bn, out_signature.data(), 32);
        BN_bn2binpad(s_final, out_signature.data() + 32, 32);
        out_signature[64] = (uint8_t)v;

        // Cleanup
        EC_KEY_free(ec_key);
        BN_free(half_n);
        BN_free(s_final);
        BN_CTX_free(ctx);
        ECDSA_SIG_free(ec_sig);
    }

    // Static Keccak-256 access for testing
    static void hash_keccak256(const uint8_t* data, size_t len, uint8_t out[32]) {
        keccak256_hash(data, len, out);
    }

private:
    EVP_PKEY* pkey_ = nullptr;
    std::string domain_type_;
    uint8_t domain_separator_[32] = {0};

    [[noreturn]] void handle_openssl_error(const std::string& msg = "") {
        unsigned long err_code;
        std::string full_msg = msg;
        while ((err_code = ERR_get_error())) {
            char err_buf[256];
            ERR_error_string_n(err_code, err_buf, sizeof(err_buf));
            full_msg += ": " + std::string(err_buf);
        }
        throw std::runtime_error("OpenSSL Error: " + full_msg);
    }
};

#pragma GCC pop_options

#endif // EIP712_SIGNER_HPP