#!/usr/bin/env bash
# Conservative host tuning.  Safe network settings apply immediately; boot/NIC
# changes require explicit flags and are never inferred from writable files.
set -euo pipefail

[[ $EUID -eq 0 ]] || { echo "Run as root." >&2; exit 1; }

HOT_CORE="${HOT_CORE:-2}"
APPLY_BOOT=0
NIC=""
for arg in "$@"; do
  case "$arg" in
    --hot-core=*) HOT_CORE="${arg#*=}" ;;
    --apply-boot) APPLY_BOOT=1 ;;
    --nic=*) NIC="${arg#*=}" ;;
    *) echo "Unknown option: $arg" >&2; exit 2 ;;
  esac
done
[[ "$HOT_CORE" =~ ^[0-9]+$ ]] || { echo "Invalid HOT_CORE" >&2; exit 2; }
[[ -z "$NIC" || "$NIC" =~ ^[A-Za-z0-9_.:-]+$ ]] || {
  echo "Invalid NIC name" >&2; exit 2;
}
(( HOT_CORE < $(nproc) )) || { echo "HOT_CORE=$HOT_CORE is not present" >&2; exit 2; }

SYSCTL_FILE=/etc/sysctl.d/99-crowdintel-client.conf
if [[ -e "$SYSCTL_FILE" ]]; then
  cp -a "$SYSCTL_FILE" "$SYSCTL_FILE.bak.$(date +%Y%m%d%H%M%S)"
fi
cat >"$SYSCTL_FILE" <<'SYSCTL'
# Outbound long-lived TLS/WebSocket client: detect dead peers and avoid slow
# start after quiet periods.  Listener backlog/port-range cargo-cult omitted.
net.ipv4.tcp_keepalive_time = 30
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_slow_start_after_idle = 0
# Moderate socket ceilings; application buffers remain independently bounded.
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
SYSCTL
sysctl --system >/dev/null
echo "Applied reversible client network settings: $SYSCTL_FILE"

if [[ -n "$NIC" ]]; then
  command -v ethtool >/dev/null || { echo "ethtool is required for --nic" >&2; exit 3; }
  ip link show "$NIC" >/dev/null
  ethtool -k "$NIC" >"/var/tmp/crowdintel-${NIC}-offload-before.txt"
  # GRO/LRO may add aggregation latency.  TSO/GSO primarily affect bulk egress;
  # leave them unchanged unless measurements on this exact NIC justify it.
  ethtool -K "$NIC" gro off lro off
  echo "Disabled GRO/LRO on $NIC; prior state saved under /var/tmp."
fi

if (( APPLY_BOOT == 0 )); then
  echo "Boot tuning skipped (pass --apply-boot after latency/power measurements)."
  exit 0
fi

if command -v systemd-detect-virt >/dev/null && systemd-detect-virt --quiet; then
  echo "Refusing boot CPU isolation inside a VM/container." >&2
  exit 4
fi

KPARAMS="isolcpus=managed_irq,${HOT_CORE} nohz_full=${HOT_CORE} rcu_nocbs=${HOT_CORE} intel_idle.max_cstate=1 processor.max_cstate=1"
if command -v update-grub >/dev/null && [[ -d /etc/default/grub.d ]]; then
  GRUB_SNIPPET=/etc/default/grub.d/99-crowdintel.cfg
  if [[ -e "$GRUB_SNIPPET" ]]; then
    cp -a "$GRUB_SNIPPET" "$GRUB_SNIPPET.bak.$(date +%Y%m%d%H%M%S)"
  fi
  # GRUB_CMDLINE_LINUX_DEFAULT is composed by this dedicated snippet rather
  # than destructively editing an existing administrator-owned line.
  cat >"$GRUB_SNIPPET" <<EOF
# Generated by kernel_tuning.sh; remove this file to roll back.
GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT:-} $KPARAMS"
EOF
  update-grub
elif command -v grubby >/dev/null; then
  grubby --update-kernel=ALL --args="$KPARAMS"
else
  echo "No supported bootloader updater (update-grub/grubby); no boot change made." >&2
  exit 5
fi

echo "Configured hot core $HOT_CORE with shallow (not disabled) C-states."
echo "Reboot required. Verify /proc/cmdline and measure p99 latency + power afterward."
